name: Rust

on:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    env: 
      REDIS: "redis://127.0.0.1:6379/"

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build debug
        run: cargo build --verbose

      - name: Build release
        run: cargo build --release --verbose
        
      - name: Run tests debug 
        run: cargo test --verbose

      - name: Run tests release
        run: cargo test --release --verbose
